version: '3.7'
services:
  MDADB:
    image: postgres
    container_name: MDADB
    restart: always
    environment:
      POSTGRES_USER: MDADB_user
      POSTGRES_PASSWORD: MDADB_pwd
      POSTGRES_DB: MDADB_sch
    volumes:
      - ./MDADB/Database:/var/lib/postgresql/data
    ports:
      - "5030:5432"